### PR TITLE
Remove medium sticky footer

### PR DESCRIPTION
**Pull request by cimke**
Removes this footer

Screenshot 2019-10-08 at 18 43 08

### CODE REVIEW

**Comment by magnolia1234** [comment]
Hides footer indeed.

**Comment by iamadamdev** [comment]
Please resolve merge conflicts

**Comment by iamadamdev** [comment]
I tested this locally (fixed merge conflicts) but the medium footer was still showing up.

**Comment by magnolia1234** [comment]
Works just fine for me. Did you include the redefined contains-function (renaming would be wise though)?

**Comment by cimke** [comment]
Hey, @magnolia1234 thanks for the advice! Changed the name 👍

**Comment by magnolia1234** [comment]
Good, maybe typo pageContain**t**s instead of pageContains?

**Comment by iamadamdev** [comment]
Please fix merge conflicts and confirm it still works. (personally for me it didn't remove the footer)

**Comment by cimke** [comment]
GPG keys messed up so I had to rebase using GitHub online tool 😶 Checked if it hides the footer and I confirm that it does ✅

**Pull request merged**
