### PR TITLE
readding support for latercera.com

### PR DESCRIPTION
**Pull request by dalacost**
latercera.com was in the list  without any specific instruction.

### CODE REVIEW

**Comment by iamadamdev** [comment]
Where/which article is this needed on? I can open most articles fine w/o this.

**Comment by dalacost** [comment]
In "pulso" section and "pulso trader" category. after some readings you get the paywall.
https://www.latercera.com/canal/pulso-trader/

**Comment by iamadamdev** [comment]
Thanks!

**Comment by zubus** [comment]
Not working now, example https://www.latercera.com/pulso-trader/noticia/goldman-sachs-destaca-medidas-del-central-y-descarta-presiones-inflacionarias/RRLPTMZBOVG5BN7WOVZY6LXXLE/

**Comment by iamadamdev** [comment]
That article seems to be behind a hard paywall. But I loaded 10+ articles from the front page and they all worked.

**Pull request merged**
