### PR TITLE
Fix Wsj/Quartz/Harpers Mag/WaPo gdpr & add Le Monde/L'Écho/La Nación & maintenance background.js

### PR DESCRIPTION
**Pull request by magnolia1234**
Fixes Wsj paywall: adding googlebot (@hamorphis), mod-rsswn is obsolete, fix for error-message: close-btn doesn't exist
Fixes issues #349, #360, #361

Fix Quartz/qz.com cookie settings

Fix Harper's Magazine cookie settings
Fixes issue #310

Fix WaPo gdpr cookie-banner (by holding on to wp_gdpr cookie).
New options to hold or drop specific cookies from the remove_cookies list (also wsjregion-cookie).
Fixes issue #22 and more. 

Add Le Monde: removing paywall while keeping article recommendations in paywall-container.
Also removes persistent cookie-banner which links to google.com (only visible with extension).
Fixes request #356

Add L'Écho & La Nación + typos/comments (@iscreamcoke)
Requests #302 & #352

Maintenance: most of sites present only in remove_cookies settings are obsolete because cookies are blocked by default (when not in allow_cookies).
* a few sites showed paywall again after removal.
Sites involved: Scientific American (not all articles are free), Seattle Times and Les Echos (@iscreamcoke)

### CODE REVIEW

**Comment by hamorphis** [comment]
👍

**Comment by wdkang123** [comment]
Thanks! it work!!!

**Comment by MPlatz1** [comment]
> Thanks! it work!!!

Where can I download working version (zip file)

**Comment by magnolia1234** [comment]
Wait for new release of @iamadamdev or use my fork https://github.com/magnolia1234/bypass-paywalls-chrome

**Comment by wdkang123** [comment]
> > Thanks! it work!!!
> 
> Where can I download working version (zip file)

to https://github.com/magnolia1234/bypass-paywalls-chrome, then .. open background.js and copy the code to replace it...

> > Thanks! it work!!!
> 
> Where can I download working version (zip file)

download it:https://github.com/magnolia1234/bypass-paywalls-chrome

**Comment by MPlatz1** [comment]
Thank you!

**Comment by magnolia1234** [comment]
Also new wsj-code in contentScript.js (block popup & banner).

**Comment by 756180** [comment]
thanks !!!!!!!!!!!!

**Comment by SantaCruzJoe** [comment]
Thank you!

**Comment by oneninetyeight** [comment]
Muchas gracias!

**Comment by iscreamcoke** [comment]
Great job

**Comment by magnolia1234** [comment]
Seems obvious to me to keep this extension working with the major sites.

**Comment by KTamas** [comment]
Thank you for this, hope it gets merged soon.

**Comment by iscreamcoke** [comment]
referencing requests #352 & #302 as completed

**Pull request merged**
