### PR TITLE
Intended to redirect issues to other contributors

### PR DESCRIPTION
**Pull request by kimkha**
@iamadamdev As you mentioned in https://github.com/iamadamdev/bypass-paywalls-chrome/pull/548#issuecomment-612662040, I think you could redirect all new site requests to me instead. (Maybe add more contributors to the list in future). I have some spare time to work on, and will send PRs for you to merge. It would be the best for you and for community. WDYT?

Note: This is just a suggestion, if you're not happy, then just close this.

### CODE REVIEW

**Comment by iamadamdev** [comment]
Thanks for the offer. I will re-open Issues soon so I won't need to redirect anywhere else.
However if you want to help field the requests (and/or submit PRs) as the issues build up that would be greatly appreciated.

However I don't want to add every site under the sun.
I want to restrict it to the most popular news sites in each country. No more local sites. But we can continue to maintain the existing ones.

**Comment by kimkha** [comment]
Fair enough. I actually want to help, so let me take a look at all the requests when you're ready to re-open the Issues tab.

**Comment by iamadamdev** [comment]
@kimkha I've re-opened Issues.

**Comment by kimkha** [comment]
Awesome. Thanks

**Comment by kimkha** [comment]
Haha, just want to note that 9 days since you re-open the issues, almost of them have gone. 💖

**Pull request closed without merging**
