### PR TITLE
Add lavoixdunord.fr

### PR DESCRIPTION
**Pull request by 6mon**

### CODE REVIEW

**Comment by CalvinWu4** [comment]
Does not work 
Seems to be behind a hard paywall
https://www.lavoixdunord.fr/903499/article/2020-12-05/lille-des-fruits-des-oignons-des-pates-une-campagne-pour-combattre-la-precarite

**Comment by 6mon** [comment]
Realy strange...
It works on my side

With:
2020-12-05-22-41-www lavoixdunord fr

Without:
2020-12-05-22-39-www lavoixdunord fr

I have UBloks, but it looks to works also without this plugin. Could there be other elements that alter the result?

**Comment by iamadamdev** [comment]
Works for me. Thanks for contributing.

**Comment by CalvinWu4** [comment]
Nvm I forgot to check the site in my list
Yup works perfectly

**Pull request merged**
