### PR TITLE
Dutch papers/magazines

### LINKED ISSUE #279: Dutch weekly magazine: www.groene.nl
New magazine request (limit of 5 articles)

### PR DESCRIPTION
**Pull request by magnolia1234**
Dutch papers: ad.nl, ed.nl (cookie fix), parool.nl, trouw.nl, volkskrant.nl (3rd party cookie)
Dutch magazines: groene.nl, vn.nl

Removed leftover cookie setting for fd.nl (hard paywall).

Closes #279, #280 & #184

### CODE REVIEW

**Comment by iamadamdev** [comment]
Thank you for your contributions!

btw @cimke if you have time I could also use help in supporting the firefox version at https://github.com/iamadamdev/bypass-paywalls-firefox

**Comment by jvdmeij** [comment]
> Dutch papers: ad.nl, ed.nl (cookie fix), parool.nl, trouw.nl, volkskrant.nl (3rd party cookie)
> Dutch magazines: groene.nl, vn.nl
> 
> Removed leftover cookie setting for fd.nl (hard paywall).
> 
> Closes #279, #280 & #184

Volkskrant seems to have stopped working unfortunately. Hope you can find a fix :)

**Comment by jim-crow-act** [comment]
> Volkskrant seems to have stopped working unfortunately. Hope you can find a fix :)

@jvdmeij
Firefox add-on seems abandoned.
Maybe ask the original commiter @magnolia1234

**Comment by iamadamdev** [comment]
if you reference the spammer or any other repo here you will be banned

**Comment by jim-crow-act** [comment]
Private repo or what (no issues)?
I just mentioned the commiter of this fix.

**Comment by jim-crow-act** [comment]
Relax, you seem be a bit high-strung ...
But @cimke is still working on this repo or has he left too?

**Pull request merged**
