### PR TITLE
Add LeParisien.fr & fix Quora & Le Monde & NzHerald & Harper's Magazine default & fix default websites in options

### PR DESCRIPTION
**Pull request by magnolia1234**
Adding French paper Le Parisien.
In cooperation with @iscreamcoke
Fixes request #363 

Fix Quora 'read more' error
Fixes issue #351

Fix Le Monde support (now all paragraphs)
Fixes issue #384

Fix NzHerald (@alastairR)
https://github.com/iamadamdev/bypass-paywalls-firefox/pull/371
Fixes issue #391

Fix Harper's Magazine default option.

Fix default websites not checked in options.
Default websites with postfix like ' (javascript disabled) are not checked in options because mismatch in key. New filter to disregard any space + text in parentheses (options.js).

### CODE REVIEW

**Comment by iscreamcoke** [comment]
So the solution was a timer, thanks for the PR. Can you add the newsletter?

```
const newsletter = document.querySelector('.margin_bottom_md');
        removeDOMElement(paywall, newsletter);
```

**Comment by magnolia1234** [comment]
Newsletter is not relevant for paywall (can be blocked by uBlock).
Timer and also removal of scroll-eventListener (blurred content again).

**Comment by iscreamcoke** [comment]
Agree, just asked because it was in the original request. Great job

**Comment by iamadamdev** [comment]
Please rebase off latest master, you won't need the versioning updates.

**Comment by magnolia1234** [comment]
This was a rebase and merge though ...

**Comment by iscreamcoke** [comment]
Do you want me to add the changes from my PR?

**Comment by magnolia1234** [comment]
No, there are no merging issues.

**Comment by iamadamdev** [comment]
Fix merge conflicts

**Comment by magnolia1234** [comment]
Fixed.

**Pull request merged**
