### PR TITLE
Support for gelocal group (italian newspapers)

### PR DESCRIPTION
**Pull request by Lychfindel**
I added support for newspapers belonging to [gelocal group](https://quotidiani.gelocal.it/edicola/home.jsp) (Italian network of local newspapers)

### CODE REVIEW

**Comment by iamadamdev** [comment]
Thanks for your contribution!

**Comment by Lychfindel** [comment]
I am sorry to say that this support does not work anymore, since the newspapers changed the way they hide the content.

**Comment by iamadamdev** [comment]
This works though? https://lanuovaferrara.gelocal.it/ferrara/cronaca/2021/02/08/news/ferrara-si-rifiuta-di-pagare-dopo-le-consumazioni-denunciato-1.39876066?amp_js_v=a6&amp_gsa=1&usqp=mq331AQHKAFQArABIA==
or is that not the whole article?

**Comment by Lychfindel** [comment]
I think that one has no paywall. But for example using the plugin with [this one](https://lanuovaferrara.gelocal.it/ferrara/cronaca/2021/02/16/news/ferrara-piange-guzzinati-al-pci-eravamo-una-famiglia-e-angelo-un-nostro-maestro-1.39908169) doesn't show the whole article, but just the first paragraph

**Comment by iamadamdev** [comment]
Try latest master

**Pull request merged**
