### PR TITLE
Change var to let & const

### PR DESCRIPTION
**Pull request by kimkha**
Just small refactoring

### CODE REVIEW

**Comment by iamadamdev** [comment]
Since you are updating contentScript.js, one more optimization we can do is add an `else if`e to each match domain since after we find one we don't need to keep searching. If you don't mind?

**Comment by kimkha** [comment]
What about `for (let i = 0; i < list.length; i++)`, should I change to `for (const item of list)`?

**Comment by iamadamdev** [comment]
> What about `for (let i = 0; i < list.length; i++)`, should I change to `for (const item of list)`?
Yes please

**Comment by kimkha** [comment]
Done.

**Comment by iamadamdev** [comment]
Thanks! Merged.

**Pull request merged**
