### PR TITLE
spam

### PR DESCRIPTION
**Pull request by iamadamdev-gh0st**

### CODE REVIEW

**Comment by Rohaq** [comment]
Is there some drama here I'm unaware of? ó_O

**Comment by Rohaq** [comment]
As far as I can see, there are two Github users made in the last two days that appear to have misleading usernames, forking from this repo.

Then there's this PR.

If this is how you operate, I'm unsurprised if your original account was blocked.

**Comment by kimkha** [comment]
I think magnolia just create new repo and send the link here to get people's attention. 🤷‍♀️

**Comment by iamadamdev-gh0st** [comment]
Oh, blessed are the ignorant (check commit-history) ...

This is just a notification for the users of his clean-repo (which lasts a bit longer).
But new users for a repo with a lot more suported sites and features are always welcome, I guess.

**Comment by llacb47** [comment]
> new users ... are always welcome

Then why did you block me from starring the repo, twice 

lol

**Comment by iamadamdev-gh0st** [comment]
@llacb47 No worries Mr. uBlock, no stars on BitBucket ;-)
But that must have been the blocking-department :-)

**Pull request closed without merging**
