### PR TITLE
Add lanacion.com.ar & lecho.be + fix typos

### PR DESCRIPTION
**Pull request by iscreamcoke**
1. Add La Nación (AR) & L'Écho (BE) to the default list.

2. Fixed some typos (hyperlinks) in readme.md & added two lines of comments in background.js

Based on @magnolia1234's fork to avoid merging issues

Closes issues #352 & #302

### CODE REVIEW

**Comment by iscreamcoke** [comment]
I noticed the cookie blocking on lesechos.fr is not working. Couldn't find a quick way to fix it, apart from manually emptying cookies for the domain.

**Comment by magnolia1234** [comment]
Thanks for your confidence in using my fork's code ;-)

**Comment by magnolia1234** [comment]
Be welcome to use my fork, but maybe stop commiting them to your own pull request (lots of double commits) ...

**Comment by iscreamcoke** [comment]
I'm going to close this PR and propose a merger with your fork. That's why I replicated your last changes

**Comment by magnolia1234** [comment]
You're welcome.

**Pull request closed without merging**
