### PR TITLE
Added scmp.com

### PR DESCRIPTION
**Pull request by CalvinWu4**
PR (https://github.com/iamadamdev/bypass-paywalls-chrome/issues/1019)

https://www.scmp.com/

Also test articles that load on page scroll

### CODE REVIEW

**Comment by iamadamdev** [comment]
This was brought up before, but where do you see a paywall in the first place?

**Comment by CalvinWu4** [comment]
https://www.scmp.com/news/hong-kong/health-environment/article/3113509/hong-kong-fourth-wave-carrie-lam-update-progress

**Comment by iamadamdev** [comment]
I'm not seeing any paywall there (in incognito mode without any extensions enabled). There are 2 bars at the top but they don't prevent you from reading the article.

**Comment by CalvinWu4** [comment]
Try scrolling down and waiting for articles to load

**Comment by iamadamdev** [comment]
Still no paywall for me.

**Comment by CalvinWu4** [comment]
Ok here's an exclusive article
https://www.scmp.com/news/hong-kong/law-and-crime/article/3113698/wife-takes-charge-money-after-hong-kong-official-us
It might be just those that have a paywall

**Comment by CalvinWu4** [comment]
SCMP definitely has a paywall though https://www.scmp.com/announcements/article/3093624/introducing-south-china-morning-posts-new-digital-subscription-plans

**Comment by iamadamdev** [comment]
I'm aware of that news but I've opened 100+ articles over the past few months and never seen a single paywall.

**Comment by CalvinWu4** [comment]
This is what the paywall looks like
image

**Comment by iamadamdev** [comment]
And you've verified this PR fixes it? (I'm unable to verify but I trust you)

**Comment by maxwellyli** [comment]
The paywall is disabled in recent articles if cookies are blocked but not for older articles. Here's an example article: https://www.scmp.com/news/hong-kong/health-environment/article/2058882/typhoons-and-storms-shook-hong-kong-2016

**Comment by iamadamdev** [comment]
Not seeing any paywall here. Do you have uBlock Origin installed?

**Comment by kristofferR** [comment]
I'm having issues with a paywall on scmp.com on this page:
https://www.scmp.com/lifestyle/arts-culture/article/3037840/stunning-photos-hong-kongs-kowloon-walled-city-show-life

The whole article pops up for a split second before the paywall activates, so a bypass is possible. Ublock Origin installed ofc, tried to remove cookies and both General Paywall bypass on/off.

Video of paywall in action:
https://streamable.com/2k5m9z

**Comment by iamadamdev** [comment]
I'm not seeing a paywall there. Try incognito mode with just uBlock Origin and my extension enabled.

**Comment by kristofferR** [comment]
Tried that, no luck.

I found the issue though, it's the default "uBlock Filters" filter that breaks it:

https://streamable.com/z12buj

(recorded on my desktop, I verified the results on my laptop with just uBlock Origin and Bypass Paywalls)

**Pull request closed without merging**
