### PR TITLE
Add scmp.com

### PR DESCRIPTION
**Pull request by devnetkc**
This add was requested in issue #851 

This is tested and works.

This PR also includes a cleanup of the FF manifest, moving the hbr.org url into alphabetical order like the rest.

### CODE REVIEW

**Comment by iamadamdev** [comment]
Where are you seeing a paywall?

**Comment by devnetkc** [comment]
This is strange.  When I turned the extension on I got the full page popup again that blocked the screen.  It did seem dismissible, however, I can't seem to get it to come back up again to take a picture 🤦🏼‍♂️

**Comment by devnetkc** [comment]
Yeah, I did more digging, I think this is an Ad blocker issue.  I will close this, as it's not bypassing any paywalls, it's merely removing a full page over view asking to sign up.

I was able to get this other message to appear as well on FF.  I don't think this is an extension meant for these kind of messages or not.  If you want me to reopen it, please comment in #851

**Comment by hanxue** [comment]
Hi @devnetkc , would you consider merging this pull request? scmp.com now has a paywall and is subscription based since 1 August 2020 - https://www.scmp.com/announcements/article/3093631/introducing-south-china-morning-posts-new-digital-subscription-plans

 
image

**Comment by iamadamdev** [comment]
@hanxue What article are you seeing an adblocker on though?

**Pull request closed without merging**
