### PR TITLE
Fix Foreign Policy

### PR DESCRIPTION
**Pull request by eandywong**

### CODE REVIEW

**Comment by magnolia1234** [comment]
Just working fine without your 'fix'.
Cookies are already blocked before loading page.

**Comment by eandywong** [comment]
> Just working fine without your 'fix'.
> Cookies are already blocked before loading page (not in allow_cookies).

But there is still a subscription popup without a close icon, only if the cookies are cleared the close icon shows up again.

**Comment by magnolia1234** [comment]
On Chrome or other Chromium browser?
Do you use an adblocker (like uBlock Origin)?
Weird, I never get a subscription popup.

**Comment by magnolia1234** [comment]
Ah, uBlock Origin blocks the popup for me.

**Comment by eandywong** [comment]
> Ah, uBlock Origin blocks the popup for me.

Thanks for the information! After enabling filter list "AdGuard Tracking Protection" or "Fanboy’s Enhanced Tracking List" in my uBlock Origin, the popup is gone.

**Pull request closed without merging**
