### PR TITLE
Add Statista

### PR DESCRIPTION
**Pull request by Camology**
Add Statista, a statistics company that charges after you look at a graph once.

### CODE REVIEW

**Comment by iamadamdev** [comment]
Have you tested this?
Just adding it to options alone isn't going to work..
Need to update background and also readme.

**Comment by Camology** [comment]
Yeah, works on their main site you can't get past to more data. Example:

You can open this site once and look at the graph:

https://www.statista.com/statistics/263401/global-apple-iphone-sales-since-3rd-quarter-2007/

But if you close it or navigate away, it will ask you to then pay without letting you see. Seems to work with just adding to the options menu.

**Comment by iamadamdev** [comment]
Does it work for you on 
https://www.statista.com/statistics/236550/percentage-of-us-population-that-own-a-iphone-smartphone/
?

**Comment by Camology** [comment]
Yep loaded the graph up immediately

**Comment by Camology** [comment]
image

**Comment by iamadamdev** [comment]
Please also add the site to the README file

**Comment by Camology** [comment]
@iamadamdev  , added to readme and background.js . Going to also pull the firefox version and do the same thing.

**Comment by alvin-leong** [comment]
Doesn't work at all. @Camology only added it to the options, background, and Readme; he didn't change any code besides that.

**Comment by Camology** [comment]
Works on my end, let's you look at any google result graph as many times as
you want without prompting to join.

**Pull request merged**
