### PR TITLE
Fix mismatch domain with fb link

### LINKED ISSUE #603: NYT, LAT prompt login when shared on facebook.
I noticed when sharing a NYT story on fb, I got a please login window from facebook. It appears suddenly, probably when the preview loads. The window has two buttons, login and cancel.  The login request which goes away on it's own by reloading the page without me touching anything, which of course flushes the story link I pasted in.  Oops. 
This happens as soon as I paste a story from these outlets in, I do not have to click post. It seems to come from the preview. 

I notice now it happens with an LAT story, and a Bloomberg story. 
Here is the most recent: 
https://www.bloomberg.com/news/articles/2020-04-29/beef-prices-hit-record-with-trump-ordering-plants-to-stay-open
. 
I am already logged in on facebook. This may be a facebook problem, not an extension problem. 
Disabling the bypass paywalls chrome extension stops this from happening. 
There does not seem to be a way to whitelist facebook on the extension, but that might work to solve this issue.

### PR DESCRIPTION
**Pull request by kimkha**
Resolves #603

### CODE REVIEW

**Comment by iamadamdev** [comment]
Fix merge conflicts please

**Comment by kimkha** [comment]
Done

**Comment by iamadamdev** [comment]
Thanks

**Comment by Steevow** [comment]
I was the reporter, should I test the new release?

**Comment by kimkha** [comment]
@Steevow yes, please.

**Comment by Steevow** [comment]
I guess I don't know where to find it. I found the current zip, but it does not have a release number and it is the same size as the last one. So which should I try? I am not that familiar with github.

**Comment by iamadamdev** [comment]
It's already been merged to latest master, try following the instructions here:
https://github.com/iamadamdev/bypass-paywalls-chrome#installation-instructions

To confirm you are on the correct version, after installing, clicking on the newspaper icon should say v1.7.1

**Comment by iamadamdev** [comment]
@kimkha 
Are you seeing this error after browsing a few sites?
This PR looks like the culprit:
image

**Pull request merged**
