### PR TITLE
Add science-et-vie.com

### LINKED ISSUE #689: New site request: [https://www.science-et-vie.com].
Could you please add Science et vie [https://www.science-et-vie.com/].
Example article: "https://www.science-et-vie.com/science-et-culture/n-uds-une-etudiante-en-maths-resout-une-enigme-vieille-de-50-ans-56413".

Confirmed

### PR DESCRIPTION
**Pull request by kimkha**
Resolves #689

### CODE REVIEW

**Comment by iamadamdev** [comment]
At a minimum these files need to be updated: README.md, manifest-ff.json, src/js/sites.js, and possibly src/js/background.js, and/or src/js/contentScript.js.

**Comment by kimkha** [comment]
I know, but this one is weird, I only changed in background.js, and it works. No need to add sites.js.

**Comment by iamadamdev** [comment]
I see, you are just adding it to the general bypass paywall list.
However we still need to add it to the manifest for Firefox.

**Comment by kimkha** [comment]
Okay, updated.

**Comment by iamadamdev** [comment]
thanks!

**Pull request merged**
