### PR TITLE
Fix syntax errors

### PR DESCRIPTION
**Pull request by filbo**

### CODE REVIEW

**Comment by mrjohnson-tree** [comment]
I wondered already why a lot of sites weren't working ...

**Comment by iamadamdev** [comment]
Thanks, on your previous PR I briefly tested it on a few sites and it worked, but overlooked these.

**Comment by mrjohnson-tree** [comment]
This script failed for all sites.

**Comment by iamadamdev** [comment]
Works fine for me. (tested telegraph, theathletic, WSJ, etc)

**Comment by mrjohnson-tree** [comment]
Contentscript failed, before this fix.
No proper testing for errors.

**Comment by filbo** [comment]
Yes, it was my fault for making last-second changes right before commit and not properly checking my work :(

**Pull request merged**
