### PR TITLE
WIP - Remove harpers.org paywall msg

### LINKED ISSUE #310: Harper's Mag not Working :/
Hiya, 

 extension seems to have stopped working for Harper's Mag. Would greatly appreciate it if it could get fixed. Thanks for your work -- it's been great reading articles I wasn't able to read before. You're a life-changer!!

### PR DESCRIPTION
**Pull request by cimke**
Closes #310 

Hey,
I made this one WIP (Work In Progress) because I'm stuck a little and need your help.

The issue is that I don't know why my changes work only in `harpers.org` but not in any article, for example, [this article](https://harpers.org/archive/2013/11/the-man-who-saves-you-from-yourself/) isn't affected by the "rules set" I've added in the PR.

Looking for suggestions on what I've forgotten. Maybe one of you @iscreamcoke or @magnolia1234 could take a look?

### CODE REVIEW

**Comment by magnolia1234** [comment]
A 'simple' cookie-fix removes the paywall for me though.
No need for a fix via contentScript.js.

**Comment by iscreamcoke** [comment]
Hi, as @magnolia1234 has pointed out, the paywall is apparently only controlled by the cookie counter. I've just realised I had never a paywall on harpers because I had a cookie blocker extension in force all the time. Unless proved wrong, Magnolia's PR should solve the issue.

**Comment by magnolia1234** [comment]
PR #357

**Comment by cimke** [comment]
Thank you both for the responses. 

I'm closing the PR because this will be fixed in #357

**Pull request closed without merging**
