### PR TITLE
restricted permissions instead of <all_urls>

### PR DESCRIPTION
**Pull request by ttuygun**
Edit:
I cannot write new message because of restrictions so I write messages as edit.
@iamadamdev I updated the complete list of sites.
@kimkha some users like me has security/privacy concerns about injecting a script the all sites. On the other hand, less extension (or injecting extension code) provides more stable browser experience in terms of consistency.

### CODE REVIEW

**Comment by iamadamdev** [comment]
This is missing a lot of sites.

**Comment by kimkha** [comment]
Why should we restrict site permissions? Any benefit?

**Comment by sevilla2021** [comment]
Maybe less site permissions for privacy and efficiency?

**Comment by kimkha** [comment]
Well, in case of mine, I usually add more sites to the extension, and less code changes mean less headache.

**Comment by sevilla2021** [comment]
Privacy is inconvenient, you mean?
Firefox also has restricted permissions.

**Comment by kimkha** [comment]
> Firefox also has restricted permissions.

Oh, right. Then ignore my comments.

IMHO, an extension that touched too many websites is the same with all sites. And this extension is delivered with its source code, so anyone could change/remove any parts if they don't like. So, that's the reason I was asking why privacy matters here? The extension does nothing to track users' behavior, except Google Analytics which is easily removed in the code.

Again, I'm not trying to prevent my idea, just saying what I'm thinking, and let the owner choose. 😄

**Comment by sevilla2021** [comment]
Only a few users would (or want) to edit the sourcecode.
Let alone considering updates.
More important unsupported sites should not be bothered.

**Comment by kimkha** [comment]
> Only a few users would (or want) to edit the sourcecode.

True, but I don't think there is a privacy concern with this extension either. The extension does nothing. It should be fine if it could access all sites.

I want to raise this issue (and including the firefox one that we could come with `all_urls` again), because it's against #669. I feel it's better for the extension if we adopt that PR instead of this.

**Comment by kimkha** [comment]
> More important unsupported sites should not be bothered.

Forgot to reply on that, but I don't think the unsupported sites is bothered now (after my PR #665). So no code inject to unsupported sites. Which also means that the extension is super clean. 😄

**Comment by ttuygun** [comment]
> #669

Optional permission to <all_urls> solves the problem. This [extension](https://github.com/mauricelam/ScrollMaps) use it. It [keeps](https://github.com/mauricelam/ScrollMaps/blob/36ba6c82ec/manifest_template.json#L49) `<all_urls>` permission as optional and it request a new site permission whenever the user adding new domain url.

> Well, in case of mine, I usually add more sites to the extension, and less code changes mean less headache.
This also can be maintainable one js file if we automate the generate manifest.json file.

**Comment by sevilla2021** [comment]
> > More important unsupported sites should not be bothered.
> 
> Forgot to reply on that, but I don't think the unsupported sites is bothered now (after my PR #665). So no code inject to unsupported sites. Which also means that the extension is super clean. 😄

That's just for contentscript.
Background script (with GA) is also active on unsupported sites.

**Comment by sevilla2021** [comment]
> I want to raise this issue (and including the firefox one that we could come with `all_urls` again), because it's against #669. I feel it's better for the extension if we adopt that PR instead of this.

Really, <all_urls> for Firefox also?

**Comment by kimkha** [comment]
> Optional permission to <all_urls> solves the problem.

Oh, that would be great.

> Really, <all_urls> for Firefox also?

Yes, that's why I mentioned to let owner decide, and I'm not the owner. Privacy concern is good, but there is not much different on this extension.

**Comment by iamadamdev** [comment]
Privacy-conscious users can use Firefox.
Others that want custom sites can use Chrome.

**Pull request closed without merging**
