### PR TITLE
Moved to new repo - Load all sites from file & block general paywall-scripts & add Caixin Global/Scribd/Tech in Asia/Newcastle Herald/The Athletic & fix Economist/Nrc.nl/MIT Tech Review/Dn.se/photos AFR/Globe and Mail/Handelsblatt & remove Dynamed

### PR DESCRIPTION
**Pull request by magnolia1234**
Load all sites (+ custom) from json-file (sites.json).
Less maintenance because defaultSites are obsolete (in background/options.js).
Domains by default are added to allow/remove_cookies (just a few allow_cookies entries are left).
Custom sites for smaller sites and quick updates (json-file read directly from GitHub repo).
Less familiar sites currently in BP could also be transfered to the custom list.
Proposal #445 & #389

Block general paywall-scripts (also in options)
Block paywall-scripts like TinyPass/Piano (Economist, Spectator, Foreign Policy etc.) and Poool.fr (Challenges.fr).
New seperate option for these scripts (or in future by default?).
PS can also be blocked by uBlock Origin with Fanboy's Enhanced Trackers List

Allow cookies for sites with Googlebot user-agent.
Also sort Googlebot-sites (double entries).

Add Caixin Global.
Already in Firefox add-on.
Request #446

Add Tech in Asia @winstonma
Request #444 & #465

Add Newcastle Herald
Already in Firefox add-on (old domain)
Request #469

Fix Economist (Javascript/cookies); mobile menu is no longer working.
Fixes issue #474

Fix Nrc.nl (paywall).
New paywall-overlay for specific articles (test?).

Fix Dagens Nyheter (dn.se)
Hold on to edition-cookie (by only dropping id-cookie).
Fixes issue #460

Fix Toronto Star (enable Javascript)
Fix Australian Financial Review (enable Javascript/photos)

Fix Globe and Mail (enable Javascript/photos, no video and photo gallery though)
Update: clear in-memory cache for Webrequest to work correctly (block or not block specific G&B-Javascript).
Fixes issue #476

Fix Handelsblatt (Googlebot)
Fixes issue #477

Fix LeParisien.fr (block TinyPass paywall).
Fix LesEchos.fr (block TinyPass paywall).

From @iscreamcoke
* Add Scribd (unblur text of documents)
* Add The Athletic  #454,  #426, #337, #140
* Fix TheTimes.co.uk (remove subscription-block)
* Fix for MIT Tech Review (click the buttons to expand article and close banner)
* Fix Bloomberg, Asia Nikkei & Haaretz.com (banners)
* Refresh the current tab after saving options
* Deprecate Dynamed #461
* Fix Hbr.org banner

Readme.md:
* Installation instructions for Yandex browser on Android
* Table of contents
* Instruction for Fanboy's Enhanced Trackers List (block paywall-scripts)

### CODE REVIEW

**Comment by magnolia1234** [comment]
Current custom list:
  "American Affairs": "americanaffairsjournal.org",
  "Dark Reading": "darkreading.com",
  "Pittsburgh Post Gazette": "post-gazette.com",
  "The Sacramento Bee (free articles only)": "sacbee.com",
  "Tubantia": "tubantia.nl"

**Comment by iscreamcoke** [comment]
Great idea! Some suggestions:
* Select all custom sites by checking '----- custom sites (remove cookies) -----' in options
* Add 'Loeb Classical Library' to custom list
* Add a 'Reset' button in options to restore the checked items to its original state
* Maybe create two separate sections for main sites and custom sites for clarity

**Comment by magnolia1234** [comment]
I haven't spent much time in the user interface (extra checkbox as marker).

But the list is read from GitHub repository and not locally anymore (quicker updates and no more waiting for new release).
Custom sites get updated when the options are saved.
Further, the lists are merged in the options (enabledSites).

If the this PR is merged the custom list has to be mentioned though (to enable the custom options).
Maybe an extra link to sites_custom.js in readme.md.

**Comment by magnolia1234** [comment]
@iscreamcoke is working on some text enhancements and moving of sites to the custom list in my fork: https://github.com/magnolia1234/bypass-paywalls-chrome/pull/14

**Comment by iscreamcoke** [comment]
Referencing issue #452 ('pls add http://www.caixin.com/') to the PR

**Comment by iscreamcoke** [comment]
I have proposed[ another PR](https://github.com/magnolia1234/bypass-paywalls-chrome/pull/15) on Magnolia's repo, with the following features: 'Refresh the current tab after options.js is saved; Add installation instructions for Yandex browser'

**Comment by magnolia1234** [comment]
Auto-update method?
PS I don't get a notification when you update a comment.

**Comment by iscreamcoke** [comment]
PS: my request to add poool.fr to the Fanboy's lists [has been accepted](https://github.com/ryanbr/fanboy-adblock/issues/1280). Subscribing to the Enhanced Tracking List, as we advised so in the readme, will bypass many paywalls not supported by BP (tested at least on oglobo.globo.com, challenges.fr, valeursactuelles.fr)

**Comment by magnolia1234** [comment]
Good.
I think it will also be possible to add these paywall-scripts to the general Javascript-blocking routine of BP.

**Comment by iscreamcoke** [comment]
The list of non-BP-supported websites it'll bypass is quite limited limited for the moment. I just know that blocking `tinypass.com` unlocks O Globo, and that blocking `poool.fr` unlocks the two others.
But yeah blocking the specific script involved per each domain is preferable _per se_.

**Comment by iscreamcoke** [comment]
Alternatively, we could create our own uB list pointing specifically to each domain `||tinypass.com^$domain=oglobo.globo.com`

**Comment by iscreamcoke** [comment]
The list of non-BP-supported websites this method will bypass is quite limited for the moment. I just know that blocking `tinypass.com` unlocks O Globo, and that blocking `poool.fr` unlocks the two others.

But yeah blocking the specific script per domain is preferable _per se_. Alternatively, we could create our own uB list pointing specifically to each domain `||tinypass.com^$domain=oglobo.globo.com`. I guess Fanboy will do a global ban instead (e.g., `||poool.fr^$third-party`)

**Comment by magnolia1234** [comment]
Yes, both are already in Fanboy's Enhanced Tracking list (blocking all 3rd-party requests). He uses a update-interval of 5 days (update manually).

**Comment by iscreamcoke** [comment]
I think you push to a v2.0 with all the commits and features added in this PR haha

**Comment by magnolia1234** [comment]
Refactoring almost done ;-)

**Comment by iscreamcoke** [comment]
Since you're now using a json file for all sites, you can use special characters and render proper name for La Nación, Les Échos, and L'Écho ;)

**Comment by magnolia1234** [comment]
> Why in both sites.json and sites_custom.json though?

I'm not sure in which list they will end up, but only shown once in options anyway.

**Comment by iscreamcoke** [comment]
Dude I've done a fresh install of Chrome Canary, got the fork from your repo and still had this cookie issue on The Atlantic.

I'm going to try on my Windows partition when I get back from work this evening.

**Comment by magnolia1234** [comment]
Well it's mister, to you ;-)
But strange, 'only' a cookie issue on The Atlantic.
Have you checked the Chrome DevTools though?

Btw with your serial-commits  you've managed to get your notifications in my spam-folder ;-)

**Comment by iscreamcoke** [comment]
No, the issue is still general. On my fresh Chrome Canary, it’s gonna log me out if I’m connected to GitHub, Google, Twitter, etc. while I install the app. I won’t be able to connect until I uncheck all, refresh, check all, refresh.

I've tested on Opera, same issue. This is almost certainly a MacOS (Catalina?) problem

**Comment by magnolia1234** [comment]
Maybe a Mac-problem or (proxy)connection.
Have you tried to disable Medium (previous version fixed problems with Medium-content in mail).
Lots of the sites you named should not be effected by BP though ...

**Comment by iscreamcoke** [comment]
Haha sorry, I've just realised I had answered in the PR earlier today.

I'm going to search if similar issues have been reported on MacOS, especially on the last version (Catalina)

**Comment by iscreamcoke** [comment]
It's a great idea to block specific scripts rather than Javascript for the whole URL. Thank you for the recent commits Magnolia

**Comment by iscreamcoke** [comment]
Could you just block those two invasive banners on the Washington Post ? they literally take 3/2 of the page (default lists on uBlock)

Screenshot 2020-01-03 at 20 08 49
Screenshot 2020-01-03 at 20 09 07

**Comment by iscreamcoke** [comment]
The one below may be a newsletter banner, blocking scripts from `subscribe.washingtonpost.com/paywall` may be a good idea

**Comment by iscreamcoke** [comment]
Bug: if the custom list is now reachable, all of the list (including local .json files) won't load  in options.

**Comment by magnolia1234** [comment]
Enable uBlock Origin for WaPo banners (or make PR).
I'm not getting these (even without adblocker).

**Comment by magnolia1234** [comment]
> Bug: if the custom list is not reachable at github.com, all of the list (including local .json files) won't load in options.

Without a internet connection you can't open websites either.
Or did you edit the url?

**Comment by iscreamcoke** [comment]
Without a internet connection you can't open websites either.
Or did you edit the url?

I edited the url indeed

It could cause an uncommon issue: when github.com is down, the options won't load in BP

**Comment by iscreamcoke** [comment]
PS: typo in `background.js` > `var blockedRegexes` > `newcastleherald.com.au` > `tinypas` (tinypass)

**Comment by magnolia1234** [comment]
The regular expression matches anyway.
PS please do something 'productive' and block some banners ;-)

**Comment by magnolia1234** [comment]
> Bug: if the custom list is not reachable at github.com, all of the list (including local .json files) won't load in options.

When I use an incorrect url for custom sites I only get the sites from local sites.json.
I could add the local alternative though.
Only when I go offline I end up with an empty options-page, but then first the Google Analytics-script can't be loaded (crashes background.js?).

**Comment by mcmicahelchan** [comment]
@magnolia1234 Hi there. Is it possible to support caixin.com, thx~

**Comment by magnolia1234** [comment]
Free at last ;-)
https://github.com/magnolia1234/bypass-paywalls-chrome-clean

**Comment by iamadamdev** [comment]
This PR is broken.

**Pull request closed without merging**
