### PR TITLE
Add unionleader.com

### PR DESCRIPTION
**Pull request by ben-burns**
Paywall bypass for the New Hampshire Union Leader news website ([unionleader.com](https://unionleader.com)).

### CODE REVIEW

**Comment by llacb47** [comment]
You can just remove cookies, or block a few scripts with uBlock Origin. Same with most Town News sites.

**Comment by ben-burns** [comment]
> You can just remove cookies, or block a few scripts with uBlock Origin. Same with most Town News sites.

Unfortunately, out of the box uBlock origin with all the filters enabled as well as using Cookie Remover didn't resolve paywall in my instance on FF.  Using this in my fork so figured upstream may find it useful.  If not, no sweat! :)

**Comment by llacb47** [comment]
All you need to block the paywall is to add the uBlock Origin filter:
`||townnews.com^*/tncms/*/metering/`

**Comment by ben-burns** [comment]
@llacb47 Thanks!  I'll close this out since that filter does the trick.

**Pull request closed without merging**
