### PR TITLE
Add Süddeutsche Zeitung

### PR DESCRIPTION
**Pull request by ajoub**

### CODE REVIEW

**Comment by iamadamdev** [comment]
Have you tested if this works?

**Comment by ajoub** [comment]
> Have you tested if this works?

Yes I have and it works.

### Method

1. Remove check mark next to Süddeutsche Zeitung in the options menu
2. Read a couple of articles
3. Hit paywall
4. Apply check mark next to Süddeutsche Zeitung in the options menu
5. Read article

**Comment by iamadamdev** [comment]
It does not bypass https://www.sueddeutsche.de/wissen/ernaehrung-tiefkuehlkost-abnehmen-1.4517913?reduced=true

Besides SZ Plus articles, where are you seeing a paywall? The 'Exklusiv' ones?
With uBlock Origin installed I am not seeing a paywall at all except on SZ Plus articles.

**Comment by ajoub** [comment]
> It does not bypass https://www.sueddeutsche.de/wissen/ernaehrung-tiefkuehlkost-abnehmen-1.4517913?reduced=true
> 
> Besides SZ Plus articles, where are you seeing a paywall? The 'Exklusiv' ones?
> With uBlock Origin installed I am not seeing a paywall at all except on SZ Plus articles.

Morning, I have just tested the following two articles and I get a paywall with this extension disabled and no paywall with the extension enabled:

- https://www.sueddeutsche.de/wissen/klimawandel-wald-1.4515837
- https://www.sueddeutsche.de/muenchen/fuerstenfeldbruck/klimawandel-streit-ueber-brucker-e-mobil-foerderung-1.4518024

However, I do get a paywall at the URL you provided. Note that the paywall at that URL doesn't give a warning about number of articles read, whereas the paywall in the above mentioned two URL does.

**Comment by iamadamdev** [comment]
Do you have uBlock Origin installed?
I can view those 2 articles just fine w/o my extension enabled.

**Comment by ajoub** [comment]
> Do you have uBlock Origin installed?
> I can view those 2 articles just fine w/o my extension enabled.

Yes I do have uBlock origin installed. Have you visted enough articles before loading those? I need to click on about 10 articles before I hit the paywall.

**Comment by iamadamdev** [comment]
In that case my Cookie Remover should do the trick and we don't need to add the site to Bypass Paywalls
https://chrome.google.com/webstore/detail/cookie-remover/kcgpggonjhmeaejebeoeomdlohicfhce

**Pull request closed without merging**
