### PR TITLE
Add Dark Reading & The Canberra Times

### PR DESCRIPTION
**Pull request by iscreamcoke**
1. Add darkreading.com, canberratimes.com.au

Request #367

2. Add a 'return' button linking options.html to popup.html

thanks to @magnolia1234 for support

### CODE REVIEW

**Comment by iamadamdev** [comment]
What's with the changes to the other sites? Those were unnecessary measures for them?

**Comment by iscreamcoke** [comment]
I managed to get a partial bypass for Le Parisien's paywall, but I let it aside for the moment as the content will keep blur while the style of their class is removed (only becomes readable when I inspect the element in Chrome for no apparent reason).

The other bypasses I did have already been merged in last @magnolia1234's PR

**Comment by iscreamcoke** [comment]
Here's the code for information and archiving:

```
if (window.location.href.indexOf("leparisien.fr") !== -1) {
    
        const paywall = document.querySelector('.relative.piano-paywall.below_nav.sticky');
        const newsletter = document.querySelector('.margin_bottom_md');
        removeDOMElement(paywall, newsletter);

        var content = document.getElementsByClassName('content');
        for (var i = 0; i < content.length; i++) {
        content[i].removeAttribute("style");
    }
}
```

**Comment by iscreamcoke** [comment]
Everything's good now @iamadamdev. My background.js was based on an older version

**Comment by iscreamcoke** [comment]
Well it appears I had a sync bug with git. Messed up with my background.js. Everything should be good now @iamadamdev.

**Comment by iscreamcoke** [comment]
Screenshot 2019-10-28 at 00 59 22
Right change list for background.js

**Comment by iscreamcoke** [comment]
Screenshot 2019-10-28 at 00 59 22
List of changes for background.js. There's no difference in spacing in Sublime Text. Don't know why the last part is highlighted.

**Pull request closed without merging**
