### PR TITLE
Add some metropolitan news in Australia

### PR DESCRIPTION
**Pull request by kimkha**
Kind of re-open of this PR https://github.com/iamadamdev/bypass-paywalls-chrome/pull/372

### CODE REVIEW

**Comment by johniss** [comment]
yeah, and there's any chance to add some main-stream german sites e.g.: zeit.de, sueddeutsche.de, faz.net? thank you so much for your effort!

**Comment by kimkha** [comment]
@johniss I don't know German, it's hard for me to find out. Sorry. I'm in Australia, which is why I want to bypass these websites.

@iamadamdev Would you mind to take a look?

**Comment by iamadamdev** [comment]
@kimkha Looks good, can you also add the sites to manifest-ff.json since the FF repo will eventually be merged with this one?

**Comment by kimkha** [comment]
@iamadamdev I just did force push, you don't have to do it in my PR, btw. Haha. Just take a glance.

**Comment by kimkha** [comment]
oh, I misunderstood the message.

Screen Shot 2020-04-20 at 09 36 04

**Comment by iamadamdev** [comment]
I moved around some files so please rebase off latest master.

**Comment by kimkha** [comment]
Done

**Comment by iamadamdev** [comment]
Try again, I removed the GitHub actions.

**Comment by kimkha** [comment]
ping

**Pull request merged**
